# Generated by Django 3.2 on 2024-09-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmodels',
            options={'verbose_name': 'Тестовое задание', 'verbose_name_plural': 'Тестовые задания'},
        ),
        migrations.AlterField(
            model_name='testmodels',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
    ]
